package com.bovinemagnet.pgconsole.model;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

/**
 * Represents a historical record of a database schema comparison execution.
 * <p>
 * This class captures the metadata and summary statistics from a schema comparison
 * operation between two PostgreSQL database instances. It is used for audit logging,
 * tracking schema drift over time, and providing a historical view of schema evolution
 * and synchronisation activities.
 * <p>
 * Each record stores:
 * <ul>
 *   <li>Source and destination instance/schema identifiers</li>
 *   <li>Timestamp and user information</li>
 *   <li>Summary counts of missing, extra, modified, and matching objects</li>
 *   <li>Optional profile name and JSON snapshots for detailed analysis</li>
 * </ul>
 * <p>
 * The class provides utility methods for formatting, summarising results, and
 * detecting drift between consecutive comparison executions.
 *
 * @author Paul Snow
 * @since 0.0.0
 * @see SchemaComparisonResult
 */
public class ComparisonHistory {

    /**
     * Unique identifier for this comparison history record.
     * Typically auto-generated by the database persistence layer.
     */
    private Long id;

    /**
     * Timestamp when the schema comparison was performed.
     * Initialised to the current time when the object is created.
     */
    private Instant comparedAt;

    /**
     * Name or identifier of the source database instance.
     * Represents the baseline or reference schema being compared from.
     */
    private String sourceInstance;

    /**
     * Name or identifier of the destination database instance.
     * Represents the target schema being compared against the source.
     */
    private String destinationInstance;

    /**
     * Name of the source database schema.
     * Combined with {@link #sourceInstance} to fully identify the source.
     */
    private String sourceSchema;

    /**
     * Name of the destination database schema.
     * Combined with {@link #destinationInstance} to fully identify the destination.
     */
    private String destinationSchema;

    /**
     * Username or identifier of the user who performed the comparison.
     * Used for audit trail purposes.
     */
    private String performedBy;

    /**
     * Count of database objects present in the source but missing in the destination.
     * Indicates objects that may need to be created in the destination schema.
     */
    private int missingCount;

    /**
     * Count of database objects present in the destination but not in the source.
     * Indicates objects that may be extraneous or need to be removed from the destination.
     */
    private int extraCount;

    /**
     * Count of database objects that exist in both schemas but have structural differences.
     * Indicates objects that may need to be synchronised or updated.
     */
    private int modifiedCount;

    /**
     * Count of database objects that are identical in both schemas.
     * Higher matching counts indicate better schema alignment.
     */
    private int matchingCount;

    /**
     * Optional name of the comparison profile or configuration used.
     * May be null if no named profile was used.
     */
    private String profileName;

    /**
     * JSON snapshot of the complete comparison result.
     * Stores detailed diff information for historical analysis.
     * May be null if detailed snapshots are not retained.
     */
    private String resultSnapshotJson;

    /**
     * JSON representation of the filter configuration applied during comparison.
     * Records which object types or patterns were included/excluded.
     * May be null if default filtering was used.
     */
    private String filterConfigJson;

    /**
     * Constructs a new ComparisonHistory instance with the current timestamp.
     * The {@code comparedAt} field is initialised to {@link Instant#now()}.
     */
    public ComparisonHistory() {
        this.comparedAt = Instant.now();
    }

    /**
     * Creates a ComparisonHistory record from a schema comparison result.
     * <p>
     * This factory method extracts summary information from a {@link SchemaComparisonResult}
     * and populates a new history record with the comparison metadata, timestamp, and
     * object counts. The detailed result snapshot and filter configuration are not
     * populated by this method and may be set separately if needed.
     *
     * @param result the schema comparison result containing comparison metadata and summary statistics
     * @param username the username or identifier of the user who performed the comparison
     * @return a new ComparisonHistory instance populated with data from the result
     * @see SchemaComparisonResult
     * @see SchemaComparisonResult#getSummary()
     */
    public static ComparisonHistory fromResult(SchemaComparisonResult result, String username) {
        ComparisonHistory history = new ComparisonHistory();
        history.comparedAt = result.getComparedAt();
        history.sourceInstance = result.getSourceInstance();
        history.destinationInstance = result.getDestinationInstance();
        history.sourceSchema = result.getSourceSchema();
        history.destinationSchema = result.getDestinationSchema();
        history.performedBy = username;
        history.missingCount = result.getSummary().getMissingObjects();
        history.extraCount = result.getSummary().getExtraObjects();
        history.modifiedCount = result.getSummary().getModifiedObjects();
        history.matchingCount = result.getSummary().getMatchingObjects();
        return history;
    }

    /**
     * Returns the comparison timestamp formatted as a human-readable string.
     * <p>
     * The timestamp is formatted using the pattern "yyyy-MM-dd HH:mm:ss" in the
     * system's default time zone. This format is suitable for display in UI tables
     * and reports.
     *
     * @return the formatted date and time string, or "-" if the timestamp is null
     * @see DateTimeFormatter
     * @see ZoneId#systemDefault()
     */
    public String getComparedAtFormatted() {
        if (comparedAt == null) return "-";
        return DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                .withZone(ZoneId.systemDefault())
                .format(comparedAt);
    }

    /**
     * Calculates the total number of schema differences detected in this comparison.
     * <p>
     * This is the sum of missing, extra, and modified object counts. A return value
     * of zero indicates that the schemas are identical (excluding matching objects).
     * This metric is useful for quickly assessing the magnitude of schema drift.
     *
     * @return the total count of differences (missing + extra + modified)
     * @see #getMissingCount()
     * @see #getExtraCount()
     * @see #getModifiedCount()
     */
    public int getTotalDifferences() {
        return missingCount + extraCount + modifiedCount;
    }

    /**
     * Returns a concise description of the comparison showing the schema mapping.
     * <p>
     * The description is formatted as "sourceInstance.sourceSchema → destinationInstance.destinationSchema",
     * providing a clear visual representation of which schemas were compared.
     * This format is suitable for display in lists, tables, and summary views.
     *
     * @return a formatted string describing the source and destination schemas
     */
    public String getDescription() {
        return String.format("%s.%s → %s.%s",
                sourceInstance, sourceSchema,
                destinationInstance, destinationSchema);
    }

    /**
     * Returns a human-readable summary text describing the comparison result.
     * <p>
     * Returns "Identical" if no differences were detected (total differences equals zero),
     * otherwise returns a formatted string indicating the number of differences found.
     * This method is useful for displaying quick status information in UI components.
     *
     * @return "Identical" if schemas match, or "{count} differences" if they differ
     * @see #getTotalDifferences()
     */
    public String getSummaryText() {
        if (getTotalDifferences() == 0) {
            return "Identical";
        }
        return String.format("%d differences", getTotalDifferences());
    }

    /**
     * Returns the appropriate Bootstrap CSS class name based on the comparison result.
     * <p>
     * The CSS class is selected based on the severity and type of differences found:
     * <ul>
     *   <li>"bg-success" - Schemas are identical (no differences)</li>
     *   <li>"bg-warning text-dark" - Missing or modified objects detected (requires attention)</li>
     *   <li>"bg-info" - Only extra objects present (informational)</li>
     * </ul>
     * This method is designed for use in Bootstrap-based UI templates to visually
     * indicate the comparison status with colour coding.
     *
     * @return a Bootstrap CSS class name appropriate for the comparison result
     * @see #getTotalDifferences()
     */
    public String getSummaryCssClass() {
        if (getTotalDifferences() == 0) {
            return "bg-success";
        } else if (missingCount > 0 || modifiedCount > 0) {
            return "bg-warning text-dark";
        } else {
            return "bg-info";
        }
    }

    /**
     * Determines whether this comparison shows schema drift compared to a previous comparison.
     * <p>
     * Drift is detected when the counts of missing, extra, or modified objects differ
     * between this comparison and the previous one. This indicates that the schema
     * synchronisation status has changed over time, either improving or degrading.
     * <p>
     * This method is useful for alerting when schemas diverge further or for tracking
     * whether synchronisation efforts are reducing drift.
     *
     * @param previous the previous ComparisonHistory record to compare against, may be null
     * @return {@code true} if drift is detected (any count differs), {@code false} if the
     *         previous comparison is null or all counts are identical
     * @see #getTotalDifferences()
     */
    public boolean hasDriftFrom(ComparisonHistory previous) {
        if (previous == null) return false;
        return missingCount != previous.missingCount
                || extraCount != previous.extraCount
                || modifiedCount != previous.modifiedCount;
    }

    // Getters and Setters

    /**
     * Returns the unique identifier for this comparison history record.
     *
     * @return the record ID, or null if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for this comparison history record.
     *
     * @param id the record ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the timestamp when the schema comparison was performed.
     *
     * @return the comparison timestamp
     */
    public Instant getComparedAt() {
        return comparedAt;
    }

    /**
     * Sets the timestamp when the schema comparison was performed.
     *
     * @param comparedAt the comparison timestamp to set
     */
    public void setComparedAt(Instant comparedAt) {
        this.comparedAt = comparedAt;
    }

    /**
     * Returns the name or identifier of the source database instance.
     *
     * @return the source instance name
     */
    public String getSourceInstance() {
        return sourceInstance;
    }

    /**
     * Sets the name or identifier of the source database instance.
     *
     * @param sourceInstance the source instance name to set
     */
    public void setSourceInstance(String sourceInstance) {
        this.sourceInstance = sourceInstance;
    }

    /**
     * Returns the name or identifier of the destination database instance.
     *
     * @return the destination instance name
     */
    public String getDestinationInstance() {
        return destinationInstance;
    }

    /**
     * Sets the name or identifier of the destination database instance.
     *
     * @param destinationInstance the destination instance name to set
     */
    public void setDestinationInstance(String destinationInstance) {
        this.destinationInstance = destinationInstance;
    }

    /**
     * Returns the name of the source database schema.
     *
     * @return the source schema name
     */
    public String getSourceSchema() {
        return sourceSchema;
    }

    /**
     * Sets the name of the source database schema.
     *
     * @param sourceSchema the source schema name to set
     */
    public void setSourceSchema(String sourceSchema) {
        this.sourceSchema = sourceSchema;
    }

    /**
     * Returns the name of the destination database schema.
     *
     * @return the destination schema name
     */
    public String getDestinationSchema() {
        return destinationSchema;
    }

    /**
     * Sets the name of the destination database schema.
     *
     * @param destinationSchema the destination schema name to set
     */
    public void setDestinationSchema(String destinationSchema) {
        this.destinationSchema = destinationSchema;
    }

    /**
     * Returns the username or identifier of the user who performed the comparison.
     *
     * @return the username
     */
    public String getPerformedBy() {
        return performedBy;
    }

    /**
     * Sets the username or identifier of the user who performed the comparison.
     *
     * @param performedBy the username to set
     */
    public void setPerformedBy(String performedBy) {
        this.performedBy = performedBy;
    }

    /**
     * Returns the count of objects present in source but missing in destination.
     *
     * @return the missing objects count
     */
    public int getMissingCount() {
        return missingCount;
    }

    /**
     * Sets the count of objects present in source but missing in destination.
     *
     * @param missingCount the missing objects count to set
     */
    public void setMissingCount(int missingCount) {
        this.missingCount = missingCount;
    }

    /**
     * Returns the count of objects present in destination but not in source.
     *
     * @return the extra objects count
     */
    public int getExtraCount() {
        return extraCount;
    }

    /**
     * Sets the count of objects present in destination but not in source.
     *
     * @param extraCount the extra objects count to set
     */
    public void setExtraCount(int extraCount) {
        this.extraCount = extraCount;
    }

    /**
     * Returns the count of objects that exist in both schemas but differ structurally.
     *
     * @return the modified objects count
     */
    public int getModifiedCount() {
        return modifiedCount;
    }

    /**
     * Sets the count of objects that exist in both schemas but differ structurally.
     *
     * @param modifiedCount the modified objects count to set
     */
    public void setModifiedCount(int modifiedCount) {
        this.modifiedCount = modifiedCount;
    }

    /**
     * Returns the count of objects that are identical in both schemas.
     *
     * @return the matching objects count
     */
    public int getMatchingCount() {
        return matchingCount;
    }

    /**
     * Sets the count of objects that are identical in both schemas.
     *
     * @param matchingCount the matching objects count to set
     */
    public void setMatchingCount(int matchingCount) {
        this.matchingCount = matchingCount;
    }

    /**
     * Returns the optional name of the comparison profile or configuration used.
     *
     * @return the profile name, or null if no named profile was used
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the optional name of the comparison profile or configuration used.
     *
     * @param profileName the profile name to set, may be null
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }

    /**
     * Returns the JSON snapshot of the complete comparison result.
     *
     * @return the result snapshot JSON, or null if not retained
     */
    public String getResultSnapshotJson() {
        return resultSnapshotJson;
    }

    /**
     * Sets the JSON snapshot of the complete comparison result.
     *
     * @param resultSnapshotJson the result snapshot JSON to set, may be null
     */
    public void setResultSnapshotJson(String resultSnapshotJson) {
        this.resultSnapshotJson = resultSnapshotJson;
    }

    /**
     * Returns the JSON representation of the filter configuration applied during comparison.
     *
     * @return the filter configuration JSON, or null if default filtering was used
     */
    public String getFilterConfigJson() {
        return filterConfigJson;
    }

    /**
     * Sets the JSON representation of the filter configuration applied during comparison.
     *
     * @param filterConfigJson the filter configuration JSON to set, may be null
     */
    public void setFilterConfigJson(String filterConfigJson) {
        this.filterConfigJson = filterConfigJson;
    }
}
