package com.bovinemagnet.pgconsole.model;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

/**
 * Represents the result of sending a notification through a notification channel.
 * <p>
 * This class captures the outcome of attempting to deliver an alert notification
 * via a configured channel (Slack, Email, PagerDuty, etc.). It tracks both successful
 * and failed delivery attempts, providing detailed information for audit trails,
 * debugging, and notification history.
 * <p>
 * Instances are typically persisted to the database via {@code NotificationRepository}
 * to maintain a historical record of all notification attempts. This enables:
 * <ul>
 *   <li>Troubleshooting notification delivery failures</li>
 *   <li>Tracking notification frequency and patterns</li>
 *   <li>Auditing alert escalations and acknowledgements</li>
 *   <li>Monitoring notification channel health</li>
 * </ul>
 * <p>
 * The class provides a fluent builder API for constructing result objects, as well
 * as static factory methods for common success and failure scenarios.
 * <p>
 * Example usage:
 * <pre>{@code
 * NotificationResult result = NotificationResult
 *     .success(channelId, "Production Alerts", ChannelType.SLACK, "alert-123")
 *     .withResponseCode(200)
 *     .withResponseBody("{\"ok\": true}")
 *     .withAlertDetails("CONNECTION_SPIKE", "WARNING", "100 connections detected", "db-prod-01");
 * }</pre>
 *
 * @author Paul Snow
 * @version 0.0.0
 * @see NotificationChannel
 * @see com.bovinemagnet.pgconsole.service.notification.NotificationDispatcher
 * @see com.bovinemagnet.pgconsole.repository.NotificationHistoryRepository
 */
public class NotificationResult {

    /**
     * Unique identifier for this notification result record.
     * Typically auto-generated by the database upon persistence.
     */
    private Long id;

    /**
     * The database identifier of the notification channel used to send this notification.
     *
     * @see NotificationChannel#getId()
     */
    private Long channelId;

    /**
     * The human-readable name of the notification channel.
     * Useful for display purposes without requiring channel lookup.
     *
     * @see NotificationChannel#getName()
     */
    private String channelName;

    /**
     * The type of notification channel used (SLACK, EMAIL, PAGERDUTY, WEBHOOK).
     *
     * @see NotificationChannel.ChannelType
     */
    private NotificationChannel.ChannelType channelType;

    /**
     * The unique identifier of the alert that triggered this notification.
     * Corresponds to the alert's deduplication key or database ID.
     */
    private String alertId;

    /**
     * The type/category of alert (e.g., "CONNECTION_SPIKE", "SLOW_QUERY", "LOCK_DETECTED").
     * Used for categorising and filtering notification history.
     */
    private String alertType;

    /**
     * The severity level of the alert (e.g., "INFO", "WARNING", "CRITICAL").
     * Indicates the urgency of the notification.
     */
    private String alertSeverity;

    /**
     * The human-readable message content of the alert.
     * Contains the detailed description sent in the notification.
     */
    private String alertMessage;

    /**
     * The name of the PostgreSQL instance that generated the alert.
     * May be null for instance-agnostic alerts.
     */
    private String instanceName;

    /**
     * The timestamp when the notification was sent.
     * Automatically set to the current time when the object is created.
     */
    private Instant sentAt;

    /**
     * Indicates whether the notification was successfully delivered.
     * {@code true} if the channel accepted the notification, {@code false} otherwise.
     */
    private boolean success;

    /**
     * The HTTP response code returned by the notification channel's API.
     * Only applicable for HTTP-based channels (Slack, PagerDuty, Webhook).
     * A value of 0 typically indicates a non-HTTP error (e.g., network failure).
     */
    private int responseCode;

    /**
     * The response body returned by the notification channel's API.
     * May contain success confirmation or error details in JSON format.
     * Can be null for non-HTTP channels or when no response body was received.
     */
    private String responseBody;

    /**
     * The error message if the notification failed.
     * Contains exception messages, validation errors, or channel-specific error descriptions.
     * Null if the notification was successful.
     */
    private String errorMessage;

    /**
     * The escalation tier at which this notification was sent.
     * Used for multi-tier escalation policies where alerts escalate through
     * multiple channels if not acknowledged. Null for non-escalating alerts.
     */
    private Integer escalationTier;

    /**
     * The deduplication key used to prevent duplicate notifications for the same alert.
     * Channels like PagerDuty use this to group related notifications.
     * May be null for channels that don't support deduplication.
     */
    private String dedupKey;

    /**
     * Constructs a new notification result with the sent timestamp set to the current time.
     * Use the static factory methods {@link #success(Long, String, NotificationChannel.ChannelType, String)}
     * or {@link #failure(Long, String, NotificationChannel.ChannelType, String, String)} for more
     * convenient construction.
     */
    public NotificationResult() {
        this.sentAt = Instant.now();
    }

    /**
     * Creates a notification result representing a successful delivery.
     * <p>
     * This factory method constructs a result object with {@code success} set to {@code true}
     * and the {@code sentAt} timestamp initialised to the current time. Additional details
     * can be added using the fluent builder methods.
     * <p>
     * Example:
     * <pre>{@code
     * NotificationResult result = NotificationResult
     *     .success(42L, "Slack Alerts", ChannelType.SLACK, "alert-456")
     *     .withResponseCode(200)
     *     .withResponseBody("{\"ok\": true, \"message_ts\": \"1234567890.123\"}");
     * }</pre>
     *
     * @param channelId the database ID of the notification channel that sent the notification
     * @param channelName the human-readable name of the notification channel
     * @param channelType the type of notification channel (SLACK, EMAIL, etc.)
     * @param alertId the unique identifier of the alert that was notified
     * @return a new {@code NotificationResult} marked as successful
     * @see #failure(Long, String, NotificationChannel.ChannelType, String, String)
     */
    public static NotificationResult success(Long channelId, String channelName,
                                              NotificationChannel.ChannelType channelType, String alertId) {
        NotificationResult result = new NotificationResult();
        result.channelId = channelId;
        result.channelName = channelName;
        result.channelType = channelType;
        result.alertId = alertId;
        result.success = true;
        return result;
    }

    /**
     * Creates a notification result representing a failed delivery attempt.
     * <p>
     * This factory method constructs a result object with {@code success} set to {@code false}
     * and captures the error message that caused the failure. The {@code sentAt} timestamp is
     * initialised to the current time. Additional failure details (response code, response body)
     * can be added using the fluent builder methods.
     * <p>
     * Example:
     * <pre>{@code
     * NotificationResult result = NotificationResult
     *     .failure(42L, "Slack Alerts", ChannelType.SLACK, "alert-456",
     *              "HTTP 429: Rate limit exceeded")
     *     .withResponseCode(429);
     * }</pre>
     *
     * @param channelId the database ID of the notification channel that attempted to send
     * @param channelName the human-readable name of the notification channel
     * @param channelType the type of notification channel (SLACK, EMAIL, etc.)
     * @param alertId the unique identifier of the alert that failed to be notified
     * @param errorMessage a description of why the notification failed; may be an exception
     *                     message, API error, or validation error
     * @return a new {@code NotificationResult} marked as failed with the provided error message
     * @see #success(Long, String, NotificationChannel.ChannelType, String)
     */
    public static NotificationResult failure(Long channelId, String channelName,
                                              NotificationChannel.ChannelType channelType, String alertId,
                                              String errorMessage) {
        NotificationResult result = new NotificationResult();
        result.channelId = channelId;
        result.channelName = channelName;
        result.channelType = channelType;
        result.alertId = alertId;
        result.success = false;
        result.errorMessage = errorMessage;
        return result;
    }

    /**
     * Returns the Bootstrap CSS class for displaying the notification status.
     * <p>
     * Used in Qute templates to colour-code notification results:
     * <ul>
     *   <li>Success: {@code "text-success"} (green)</li>
     *   <li>Failure: {@code "text-danger"} (red)</li>
     * </ul>
     *
     * @return {@code "text-success"} if the notification succeeded, {@code "text-danger"} if it failed
     * @see #getStatusIcon()
     */
    public String getStatusCssClass() {
        return success ? "text-success" : "text-danger";
    }

    /**
     * Returns the Bootstrap Icon class for displaying the notification status.
     * <p>
     * Used in Qute templates to display an icon representing the notification outcome:
     * <ul>
     *   <li>Success: {@code "bi-check-circle-fill"} (checkmark circle)</li>
     *   <li>Failure: {@code "bi-x-circle-fill"} (X circle)</li>
     * </ul>
     *
     * @return {@code "bi-check-circle-fill"} if succeeded, {@code "bi-x-circle-fill"} if failed
     * @see #getStatusCssClass()
     */
    public String getStatusIcon() {
        return success ? "bi-check-circle-fill" : "bi-x-circle-fill";
    }

    /**
     * Returns the sent timestamp formatted as a human-readable string.
     * <p>
     * The timestamp is formatted as {@code "yyyy-MM-dd HH:mm:ss"} using the system's
     * default time zone. This method is primarily used in Qute templates for displaying
     * notification history.
     *
     * @return the formatted timestamp, or an empty string if {@code sentAt} is null
     */
    public String getSentAtFormatted() {
        if (sentAt == null) return "";
        return DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                .withZone(ZoneId.systemDefault())
                .format(sentAt);
    }

    // Builder methods for fluent API

    /**
     * Sets the HTTP response code received from the notification channel.
     * <p>
     * Typically set after receiving a response from HTTP-based channels like Slack,
     * PagerDuty, or custom webhooks. Common values include:
     * <ul>
     *   <li>200: Success</li>
     *   <li>400: Bad request (invalid payload)</li>
     *   <li>401: Unauthorised (invalid API token)</li>
     *   <li>429: Rate limit exceeded</li>
     *   <li>500: Server error</li>
     * </ul>
     *
     * @param code the HTTP response code (e.g., 200, 404, 500)
     * @return this {@code NotificationResult} for method chaining
     */
    public NotificationResult withResponseCode(int code) {
        this.responseCode = code;
        return this;
    }

    /**
     * Sets the response body received from the notification channel.
     * <p>
     * The response body typically contains JSON with success confirmation or error details.
     * For example, Slack returns {@code {"ok": true, "message_ts": "1234567890.123"}} on success,
     * or {@code {"ok": false, "error": "channel_not_found"}} on failure.
     *
     * @param body the raw response body as a string; may be JSON, XML, or plain text
     * @return this {@code NotificationResult} for method chaining
     */
    public NotificationResult withResponseBody(String body) {
        this.responseBody = body;
        return this;
    }

    /**
     * Sets the detailed alert information for this notification.
     * <p>
     * This method populates all alert-related fields in a single call, which is convenient
     * when the notification service has all alert details available. These details are stored
     * in the notification history for audit and troubleshooting purposes.
     *
     * @param type the alert type (e.g., "CONNECTION_SPIKE", "SLOW_QUERY", "LOCK_DETECTED")
     * @param severity the alert severity level (e.g., "INFO", "WARNING", "CRITICAL")
     * @param message the human-readable alert message describing the issue
     * @param instance the name of the PostgreSQL instance that generated the alert; may be null
     * @return this {@code NotificationResult} for method chaining
     */
    public NotificationResult withAlertDetails(String type, String severity, String message, String instance) {
        this.alertType = type;
        this.alertSeverity = severity;
        this.alertMessage = message;
        this.instanceName = instance;
        return this;
    }

    /**
     * Sets the escalation tier at which this notification was sent.
     * <p>
     * Escalation tiers are used in multi-level alerting where unacknowledged alerts
     * escalate through progressively more urgent channels. For example:
     * <ul>
     *   <li>Tier 1: Slack channel (initial alert)</li>
     *   <li>Tier 2: Email to on-call engineer (after 5 minutes)</li>
     *   <li>Tier 3: PagerDuty page (after 15 minutes)</li>
     * </ul>
     *
     * @param tier the escalation tier number (typically 1, 2, 3, etc.); higher numbers indicate
     *             more urgent escalation levels
     * @return this {@code NotificationResult} for method chaining
     */
    public NotificationResult withEscalationTier(int tier) {
        this.escalationTier = tier;
        return this;
    }

    /**
     * Sets the deduplication key for this notification.
     * <p>
     * Deduplication keys are used to group related notifications and prevent duplicate
     * alerts for the same underlying issue. For example, PagerDuty uses dedup keys to
     * update existing incidents rather than creating new ones when the same alert fires
     * multiple times.
     * <p>
     * The key is typically derived from the alert type and instance:
     * {@code "SLOW_QUERY:db-prod-01:query-12345"}
     *
     * @param key the deduplication key; typically a composite of alert type, instance, and
     *            identifying attributes
     * @return this {@code NotificationResult} for method chaining
     */
    public NotificationResult withDedupKey(String key) {
        this.dedupKey = key;
        return this;
    }

    // Getters and Setters

    /**
     * Returns the unique database identifier for this notification result.
     *
     * @return the notification result ID, or null if not yet persisted
     */
    public Long getId() { return id; }

    /**
     * Sets the unique database identifier for this notification result.
     *
     * @param id the notification result ID
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Returns the database ID of the notification channel that sent this notification.
     *
     * @return the channel ID
     */
    public Long getChannelId() { return channelId; }

    /**
     * Sets the database ID of the notification channel that sent this notification.
     *
     * @param channelId the channel ID
     */
    public void setChannelId(Long channelId) { this.channelId = channelId; }

    /**
     * Returns the human-readable name of the notification channel.
     *
     * @return the channel name
     */
    public String getChannelName() { return channelName; }

    /**
     * Sets the human-readable name of the notification channel.
     *
     * @param channelName the channel name
     */
    public void setChannelName(String channelName) { this.channelName = channelName; }

    /**
     * Returns the type of notification channel (SLACK, EMAIL, PAGERDUTY, WEBHOOK).
     *
     * @return the channel type
     */
    public NotificationChannel.ChannelType getChannelType() { return channelType; }

    /**
     * Sets the type of notification channel.
     *
     * @param channelType the channel type
     */
    public void setChannelType(NotificationChannel.ChannelType channelType) { this.channelType = channelType; }

    /**
     * Returns the unique identifier of the alert that triggered this notification.
     *
     * @return the alert ID
     */
    public String getAlertId() { return alertId; }

    /**
     * Sets the unique identifier of the alert that triggered this notification.
     *
     * @param alertId the alert ID
     */
    public void setAlertId(String alertId) { this.alertId = alertId; }

    /**
     * Returns the type/category of the alert.
     *
     * @return the alert type (e.g., "CONNECTION_SPIKE", "SLOW_QUERY")
     */
    public String getAlertType() { return alertType; }

    /**
     * Sets the type/category of the alert.
     *
     * @param alertType the alert type
     */
    public void setAlertType(String alertType) { this.alertType = alertType; }

    /**
     * Returns the severity level of the alert.
     *
     * @return the alert severity (e.g., "INFO", "WARNING", "CRITICAL")
     */
    public String getAlertSeverity() { return alertSeverity; }

    /**
     * Sets the severity level of the alert.
     *
     * @param alertSeverity the alert severity
     */
    public void setAlertSeverity(String alertSeverity) { this.alertSeverity = alertSeverity; }

    /**
     * Returns the human-readable message content of the alert.
     *
     * @return the alert message
     */
    public String getAlertMessage() { return alertMessage; }

    /**
     * Sets the human-readable message content of the alert.
     *
     * @param alertMessage the alert message
     */
    public void setAlertMessage(String alertMessage) { this.alertMessage = alertMessage; }

    /**
     * Returns the name of the PostgreSQL instance that generated the alert.
     *
     * @return the instance name, or null if not applicable
     */
    public String getInstanceName() { return instanceName; }

    /**
     * Sets the name of the PostgreSQL instance that generated the alert.
     *
     * @param instanceName the instance name
     */
    public void setInstanceName(String instanceName) { this.instanceName = instanceName; }

    /**
     * Returns the timestamp when the notification was sent.
     *
     * @return the sent timestamp
     */
    public Instant getSentAt() { return sentAt; }

    /**
     * Sets the timestamp when the notification was sent.
     *
     * @param sentAt the sent timestamp
     */
    public void setSentAt(Instant sentAt) { this.sentAt = sentAt; }

    /**
     * Returns whether the notification was successfully delivered.
     *
     * @return {@code true} if successful, {@code false} if failed
     */
    public boolean isSuccess() { return success; }

    /**
     * Sets whether the notification was successfully delivered.
     *
     * @param success {@code true} if successful, {@code false} if failed
     */
    public void setSuccess(boolean success) { this.success = success; }

    /**
     * Returns the HTTP response code from the notification channel's API.
     *
     * @return the HTTP response code (e.g., 200, 404, 500)
     */
    public int getResponseCode() { return responseCode; }

    /**
     * Sets the HTTP response code from the notification channel's API.
     *
     * @param responseCode the HTTP response code
     */
    public void setResponseCode(int responseCode) { this.responseCode = responseCode; }

    /**
     * Returns the response body from the notification channel's API.
     *
     * @return the response body, or null if not available
     */
    public String getResponseBody() { return responseBody; }

    /**
     * Sets the response body from the notification channel's API.
     *
     * @param responseBody the response body
     */
    public void setResponseBody(String responseBody) { this.responseBody = responseBody; }

    /**
     * Returns the error message if the notification failed.
     *
     * @return the error message, or null if the notification succeeded
     */
    public String getErrorMessage() { return errorMessage; }

    /**
     * Sets the error message for a failed notification.
     *
     * @param errorMessage the error message
     */
    public void setErrorMessage(String errorMessage) { this.errorMessage = errorMessage; }

    /**
     * Returns the escalation tier at which this notification was sent.
     *
     * @return the escalation tier, or null if not part of an escalation policy
     */
    public Integer getEscalationTier() { return escalationTier; }

    /**
     * Sets the escalation tier at which this notification was sent.
     *
     * @param escalationTier the escalation tier
     */
    public void setEscalationTier(Integer escalationTier) { this.escalationTier = escalationTier; }

    /**
     * Returns the deduplication key used to prevent duplicate notifications.
     *
     * @return the deduplication key, or null if not applicable
     */
    public String getDedupKey() { return dedupKey; }

    /**
     * Sets the deduplication key used to prevent duplicate notifications.
     *
     * @param dedupKey the deduplication key
     */
    public void setDedupKey(String dedupKey) { this.dedupKey = dedupKey; }
}
