package com.bovinemagnet.pgconsole.model;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Represents a security warning or alert detected during PostgreSQL security analysis.
 * <p>
 * Security warnings are generated by various security services when potential issues,
 * misconfigurations, or policy violations are detected in the PostgreSQL database.
 * Each warning includes a type classification, severity level, affected subject,
 * detailed description, and recommended remediation action.
 * </p>
 * <p>
 * This class uses a builder pattern for fluent construction and supports the addition
 * of arbitrary key-value details for context-specific information. Warnings are
 * timestamped at creation time for audit trail purposes.
 * </p>
 * <p><strong>Usage Example:</strong></p>
 * <pre>{@code
 * SecurityWarning warning = SecurityWarning.builder()
 *     .type(WarningType.SUPERUSER_ROLE)
 *     .severity(Severity.HIGH)
 *     .subject("app_admin")
 *     .description("Role has superuser privileges")
 *     .recommendation("Remove superuser privilege if not required")
 *     .detail("Created", "2024-01-15")
 *     .build();
 * }</pre>
 *
 * @author Paul Snow
 * @since 0.0.0
 * @see com.bovinemagnet.pgconsole.service.SecurityService
 */
public class SecurityWarning {

    /**
     * Types of security warnings that can be detected during PostgreSQL security analysis.
     * <p>
     * Each warning type represents a specific category of security concern, ranging from
     * authentication weaknesses to privilege escalation risks. The enum provides both
     * a display name for presentation and a description of the security issue.
     * </p>
     */
    public enum WarningType {
        /** A role with superuser privileges exists, posing privilege escalation risk. */
        SUPERUSER_ROLE("Superuser Role", "A role with superuser privileges exists"),

        /** A role has an expired password and should be renewed immediately. */
        EXPIRED_PASSWORD("Expired Password", "A role has an expired password"),

        /** A role password will expire soon and requires proactive renewal. */
        EXPIRING_PASSWORD("Expiring Password", "A role password will expire soon"),

        /** A login role has no password expiration set, violating password policy. */
        NO_PASSWORD_EXPIRY("No Password Expiry", "A login role has no password expiration set"),

        /** A role has more privileges than necessary for its function (principle of least privilege violation). */
        EXCESSIVE_PRIVILEGES("Excessive Privileges", "A role has more privileges than necessary"),

        /** An insecure authentication method is configured in pg_hba.conf. */
        WEAK_AUTH_METHOD("Weak Authentication", "An insecure authentication method is configured"),

        /** The public schema allows CREATE for all users, enabling potential abuse. */
        PUBLIC_SCHEMA_EXPOSED("Public Schema Exposed", "The public schema allows CREATE for all users"),

        /** A potentially dangerous extension is installed that may pose security risks. */
        DANGEROUS_EXTENSION("Dangerous Extension", "A potentially dangerous extension is installed"),

        /** A connection is not using SSL/TLS encryption, exposing data in transit. */
        NO_SSL_CONNECTION("No SSL Connection", "A connection is not using SSL/TLS encryption"),

        /** A role can bypass row-level security policies. */
        BYPASS_RLS_ROLE("Bypass RLS Role", "A role can bypass row-level security"),

        /** Trust authentication allows access without password verification. */
        TRUST_AUTHENTICATION("Trust Authentication", "Trust authentication allows access without password"),

        /** Superuser access is allowed from remote hosts, increasing attack surface. */
        REMOTE_SUPERUSER("Remote Superuser Access", "Superuser access is allowed from remote hosts"),

        /** The pgaudit extension is not installed, preventing comprehensive audit logging. */
        NO_AUDIT_LOGGING("No Audit Logging", "pgaudit extension is not installed"),

        /** Using deprecated MD5 password encryption instead of SCRAM-SHA-256. */
        MD5_PASSWORD("MD5 Password Encryption", "Using deprecated MD5 password encryption");

        private final String displayName;
        private final String description;

        /**
         * Constructs a warning type with display name and description.
         *
         * @param displayName the human-readable name for UI presentation
         * @param description the detailed description of the security issue
         */
        WarningType(String displayName, String description) {
            this.displayName = displayName;
            this.description = description;
        }

        /**
         * Returns the human-readable display name for this warning type.
         *
         * @return the display name suitable for UI presentation
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Returns the detailed description of the security issue.
         *
         * @return the description explaining what this warning type indicates
         */
        public String getDescription() {
            return description;
        }
    }

    /**
     * Severity levels for security warnings with associated priority and styling.
     * <p>
     * Each severity level has a priority value (1-5) used for sorting and filtering,
     * and a Bootstrap CSS class for consistent visual presentation across the UI.
     * Higher priority values indicate more severe issues requiring immediate attention.
     * </p>
     */
    public enum Severity {
        /** Critical severity requiring immediate remediation (priority 5). */
        CRITICAL("Critical", "bg-danger", 5),

        /** High severity requiring urgent attention (priority 4). */
        HIGH("High", "bg-warning text-dark", 4),

        /** Medium severity requiring timely remediation (priority 3). */
        MEDIUM("Medium", "bg-info", 3),

        /** Low severity requiring eventual remediation (priority 2). */
        LOW("Low", "bg-secondary", 2),

        /** Informational severity for awareness only (priority 1). */
        INFO("Info", "bg-light text-dark", 1);

        private final String displayName;
        private final String cssClass;
        private final int priority;

        /**
         * Constructs a severity level with display attributes and priority.
         *
         * @param displayName the human-readable severity name
         * @param cssClass    the Bootstrap CSS class for visual styling
         * @param priority    the numeric priority (1-5, higher is more severe)
         */
        Severity(String displayName, String cssClass, int priority) {
            this.displayName = displayName;
            this.cssClass = cssClass;
            this.priority = priority;
        }

        /**
         * Returns the human-readable display name for this severity level.
         *
         * @return the display name (e.g., "Critical", "High")
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Returns the Bootstrap CSS class for styling this severity level.
         *
         * @return the CSS class (e.g., "bg-danger", "bg-warning text-dark")
         */
        public String getCssClass() {
            return cssClass;
        }

        /**
         * Returns the numeric priority for this severity level.
         * <p>
         * Priority values range from 1 (lowest) to 5 (highest) and are used
         * for sorting warnings by urgency.
         * </p>
         *
         * @return the priority value (1-5)
         */
        public int getPriority() {
            return priority;
        }
    }

    /** The classification of this security warning. */
    private WarningType type;

    /** The severity level indicating urgency of remediation. */
    private Severity severity;

    /** The affected object or entity (e.g., role name, table name, configuration setting). */
    private String subject;

    /** Detailed description of the security issue. */
    private String description;

    /** Recommended action to resolve or mitigate the security issue. */
    private String recommendation;

    /** Additional context-specific key-value details about the warning. */
    private Map<String, String> details = new HashMap<>();

    /** Timestamp when this warning was detected. */
    private OffsetDateTime detectedAt;

    /**
     * Default constructor that initialises the detection timestamp to the current time.
     */
    public SecurityWarning() {
        this.detectedAt = OffsetDateTime.now();
    }

    /**
     * Constructs a SecurityWarning with the specified attributes.
     * <p>
     * The detection timestamp is automatically set to the current time.
     * </p>
     *
     * @param type           the type of warning (must not be null)
     * @param severity       the severity level (must not be null)
     * @param subject        the affected object or entity
     * @param description    detailed description of the issue
     * @param recommendation suggested action to resolve or mitigate the issue
     */
    public SecurityWarning(WarningType type, Severity severity, String subject,
                           String description, String recommendation) {
        this.type = type;
        this.severity = severity;
        this.subject = subject;
        this.description = description;
        this.recommendation = recommendation;
        this.detectedAt = OffsetDateTime.now();
    }

    // Getters and Setters

    /**
     * Returns the type of this security warning.
     *
     * @return the warning type, or null if not set
     */
    public WarningType getType() {
        return type;
    }

    /**
     * Sets the type of this security warning.
     *
     * @param type the warning type to set
     */
    public void setType(WarningType type) {
        this.type = type;
    }

    /**
     * Returns the severity level of this security warning.
     *
     * @return the severity level, or null if not set
     */
    public Severity getSeverity() {
        return severity;
    }

    /**
     * Sets the severity level of this security warning.
     *
     * @param severity the severity level to set
     */
    public void setSeverity(Severity severity) {
        this.severity = severity;
    }

    /**
     * Returns the affected object or entity for this warning.
     *
     * @return the subject (e.g., role name, table name), or null if not set
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the affected object or entity for this warning.
     *
     * @param subject the subject to set
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * Returns the detailed description of the security issue.
     *
     * @return the description, or null if not set
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the detailed description of the security issue.
     *
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the recommended action to resolve this security issue.
     *
     * @return the recommendation, or null if not set
     */
    public String getRecommendation() {
        return recommendation;
    }

    /**
     * Sets the recommended action to resolve this security issue.
     *
     * @param recommendation the recommendation to set
     */
    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation;
    }

    /**
     * Returns the additional context-specific details for this warning.
     * <p>
     * The returned map is mutable and may be modified directly. Never returns null.
     * </p>
     *
     * @return a map of detail key-value pairs
     */
    public Map<String, String> getDetails() {
        return details;
    }

    /**
     * Sets the additional context-specific details for this warning.
     *
     * @param details the details map to set (must not be null)
     */
    public void setDetails(Map<String, String> details) {
        this.details = details;
    }

    /**
     * Returns the timestamp when this warning was detected.
     *
     * @return the detection timestamp, or null if not set
     */
    public OffsetDateTime getDetectedAt() {
        return detectedAt;
    }

    /**
     * Sets the timestamp when this warning was detected.
     *
     * @param detectedAt the detection timestamp to set
     */
    public void setDetectedAt(OffsetDateTime detectedAt) {
        this.detectedAt = detectedAt;
    }

    // Helper Methods

    /**
     * Returns the Bootstrap CSS class for the severity badge based on the current severity level.
     * <p>
     * This method is designed for use in Qute templates to apply consistent styling.
     * If severity is not set, returns "bg-secondary" as a fallback.
     * </p>
     *
     * @return the Bootstrap CSS class (e.g., "bg-danger", "bg-warning text-dark")
     */
    public String getSeverityCssClass() {
        return severity != null ? severity.getCssClass() : "bg-secondary";
    }

    /**
     * Returns the human-readable display name for the warning type.
     * <p>
     * This method is designed for use in Qute templates for consistent presentation.
     * If type is not set, returns "Unknown" as a fallback.
     * </p>
     *
     * @return the warning type display name (e.g., "Superuser Role", "Weak Authentication")
     */
    public String getTypeDisplay() {
        return type != null ? type.getDisplayName() : "Unknown";
    }

    /**
     * Adds a context-specific detail entry to this warning.
     * <p>
     * Details provide additional information about the security issue, such as
     * creation dates, privilege grants, or configuration values. This method
     * provides a convenient alternative to calling {@code getDetails().put()}.
     * </p>
     *
     * @param key   the detail key (e.g., "Created", "Granted To")
     * @param value the detail value
     */
    public void addDetail(String key, String value) {
        this.details.put(key, value);
    }

    /**
     * Returns the Bootstrap Icons class for visual representation of this warning type.
     * <p>
     * Each warning type is mapped to an appropriate icon for intuitive visual communication
     * in the UI. If type is not set, returns "bi-exclamation-triangle" as a fallback.
     * </p>
     *
     * @return the Bootstrap Icons class name (e.g., "bi-shield-exclamation", "bi-key")
     */
    public String getIconClass() {
        if (type == null) return "bi-exclamation-triangle";
        return switch (type) {
            case SUPERUSER_ROLE, BYPASS_RLS_ROLE, REMOTE_SUPERUSER -> "bi-shield-exclamation";
            case EXPIRED_PASSWORD, EXPIRING_PASSWORD, NO_PASSWORD_EXPIRY -> "bi-key";
            case EXCESSIVE_PRIVILEGES -> "bi-person-badge";
            case WEAK_AUTH_METHOD, TRUST_AUTHENTICATION, MD5_PASSWORD -> "bi-unlock";
            case PUBLIC_SCHEMA_EXPOSED -> "bi-folder2-open";
            case DANGEROUS_EXTENSION -> "bi-plugin";
            case NO_SSL_CONNECTION -> "bi-shield-x";
            case NO_AUDIT_LOGGING -> "bi-journal-x";
        };
    }

    /**
     * Creates a new builder for fluent construction of SecurityWarning instances.
     * <p><strong>Usage Example:</strong></p>
     * <pre>{@code
     * SecurityWarning warning = SecurityWarning.builder()
     *     .type(WarningType.SUPERUSER_ROLE)
     *     .severity(Severity.HIGH)
     *     .subject("app_admin")
     *     .description("Role has unnecessary superuser privileges")
     *     .recommendation("Revoke superuser and grant specific privileges")
     *     .detail("Created", "2024-01-15")
     *     .build();
     * }</pre>
     *
     * @return a new Builder instance for constructing a SecurityWarning
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for creating SecurityWarning instances using a fluent API.
     * <p>
     * The builder pattern provides a clean and readable way to construct SecurityWarning
     * objects, especially when setting multiple optional properties. All builder methods
     * return the builder instance for method chaining.
     * </p>
     * <p><strong>Example:</strong></p>
     * <pre>{@code
     * SecurityWarning warning = SecurityWarning.builder()
     *     .type(WarningType.WEAK_AUTH_METHOD)
     *     .severity(Severity.CRITICAL)
     *     .subject("pg_hba.conf line 42")
     *     .description("Trust authentication allows access without password")
     *     .recommendation("Change to scram-sha-256 authentication")
     *     .detail("Host Pattern", "0.0.0.0/0")
     *     .detail("Database", "all")
     *     .build();
     * }</pre>
     */
    public static class Builder {
        private final SecurityWarning warning = new SecurityWarning();

        /**
         * Sets the warning type.
         *
         * @param type the warning type
         * @return this builder for method chaining
         */
        public Builder type(WarningType type) {
            warning.setType(type);
            return this;
        }

        /**
         * Sets the severity level.
         *
         * @param severity the severity level
         * @return this builder for method chaining
         */
        public Builder severity(Severity severity) {
            warning.setSeverity(severity);
            return this;
        }

        /**
         * Sets the affected subject or entity.
         *
         * @param subject the subject (e.g., role name, table name)
         * @return this builder for method chaining
         */
        public Builder subject(String subject) {
            warning.setSubject(subject);
            return this;
        }

        /**
         * Sets the detailed description of the security issue.
         *
         * @param description the description
         * @return this builder for method chaining
         */
        public Builder description(String description) {
            warning.setDescription(description);
            return this;
        }

        /**
         * Sets the recommended remediation action.
         *
         * @param recommendation the recommendation
         * @return this builder for method chaining
         */
        public Builder recommendation(String recommendation) {
            warning.setRecommendation(recommendation);
            return this;
        }

        /**
         * Adds a context-specific detail entry.
         *
         * @param key   the detail key
         * @param value the detail value
         * @return this builder for method chaining
         */
        public Builder detail(String key, String value) {
            warning.addDetail(key, value);
            return this;
        }

        /**
         * Builds and returns the configured SecurityWarning instance.
         * <p>
         * The detection timestamp is automatically set during SecurityWarning construction.
         * </p>
         *
         * @return the built SecurityWarning instance
         */
        public SecurityWarning build() {
            return warning;
        }
    }
}
