package com.bovinemagnet.pgconsole.model;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Represents a security warning or alert detected during security analysis.
 * <p>
 * Security warnings are generated by various security services when
 * potential issues or misconfigurations are detected.
 *
 * @author Paul Snow
 * @version 0.0.0
 */
public class SecurityWarning {

    /**
     * Types of security warnings that can be detected.
     */
    public enum WarningType {
        SUPERUSER_ROLE("Superuser Role", "A role with superuser privileges exists"),
        EXPIRED_PASSWORD("Expired Password", "A role has an expired password"),
        EXPIRING_PASSWORD("Expiring Password", "A role password will expire soon"),
        NO_PASSWORD_EXPIRY("No Password Expiry", "A login role has no password expiration set"),
        EXCESSIVE_PRIVILEGES("Excessive Privileges", "A role has more privileges than necessary"),
        WEAK_AUTH_METHOD("Weak Authentication", "An insecure authentication method is configured"),
        PUBLIC_SCHEMA_EXPOSED("Public Schema Exposed", "The public schema allows CREATE for all users"),
        DANGEROUS_EXTENSION("Dangerous Extension", "A potentially dangerous extension is installed"),
        NO_SSL_CONNECTION("No SSL Connection", "A connection is not using SSL/TLS encryption"),
        BYPASS_RLS_ROLE("Bypass RLS Role", "A role can bypass row-level security"),
        TRUST_AUTHENTICATION("Trust Authentication", "Trust authentication allows access without password"),
        REMOTE_SUPERUSER("Remote Superuser Access", "Superuser access is allowed from remote hosts"),
        NO_AUDIT_LOGGING("No Audit Logging", "pgaudit extension is not installed"),
        MD5_PASSWORD("MD5 Password Encryption", "Using deprecated MD5 password encryption");

        private final String displayName;
        private final String description;

        WarningType(String displayName, String description) {
            this.displayName = displayName;
            this.description = description;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getDescription() {
            return description;
        }
    }

    /**
     * Severity levels for security warnings.
     */
    public enum Severity {
        CRITICAL("Critical", "bg-danger", 5),
        HIGH("High", "bg-warning text-dark", 4),
        MEDIUM("Medium", "bg-info", 3),
        LOW("Low", "bg-secondary", 2),
        INFO("Info", "bg-light text-dark", 1);

        private final String displayName;
        private final String cssClass;
        private final int priority;

        Severity(String displayName, String cssClass, int priority) {
            this.displayName = displayName;
            this.cssClass = cssClass;
            this.priority = priority;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getCssClass() {
            return cssClass;
        }

        public int getPriority() {
            return priority;
        }
    }

    private WarningType type;
    private Severity severity;
    private String subject;
    private String description;
    private String recommendation;
    private Map<String, String> details = new HashMap<>();
    private OffsetDateTime detectedAt;

    /**
     * Default constructor.
     */
    public SecurityWarning() {
        this.detectedAt = OffsetDateTime.now();
    }

    /**
     * Constructs a SecurityWarning with the specified attributes.
     *
     * @param type           the type of warning
     * @param severity       the severity level
     * @param subject        the affected object or entity
     * @param description    detailed description of the issue
     * @param recommendation suggested action to resolve
     */
    public SecurityWarning(WarningType type, Severity severity, String subject,
                           String description, String recommendation) {
        this.type = type;
        this.severity = severity;
        this.subject = subject;
        this.description = description;
        this.recommendation = recommendation;
        this.detectedAt = OffsetDateTime.now();
    }

    // Getters and Setters

    public WarningType getType() {
        return type;
    }

    public void setType(WarningType type) {
        this.type = type;
    }

    public Severity getSeverity() {
        return severity;
    }

    public void setSeverity(Severity severity) {
        this.severity = severity;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRecommendation() {
        return recommendation;
    }

    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation;
    }

    public Map<String, String> getDetails() {
        return details;
    }

    public void setDetails(Map<String, String> details) {
        this.details = details;
    }

    public OffsetDateTime getDetectedAt() {
        return detectedAt;
    }

    public void setDetectedAt(OffsetDateTime detectedAt) {
        this.detectedAt = detectedAt;
    }

    // Helper Methods

    /**
     * Returns the CSS class for the severity badge.
     *
     * @return CSS class name
     */
    public String getSeverityCssClass() {
        return severity != null ? severity.getCssClass() : "bg-secondary";
    }

    /**
     * Returns the display name for the warning type.
     *
     * @return warning type display name
     */
    public String getTypeDisplay() {
        return type != null ? type.getDisplayName() : "Unknown";
    }

    /**
     * Adds a detail entry to the warning.
     *
     * @param key   the detail key
     * @param value the detail value
     */
    public void addDetail(String key, String value) {
        this.details.put(key, value);
    }

    /**
     * Returns the Bootstrap icon class for the warning type.
     *
     * @return icon class name
     */
    public String getIconClass() {
        if (type == null) return "bi-exclamation-triangle";
        return switch (type) {
            case SUPERUSER_ROLE, BYPASS_RLS_ROLE, REMOTE_SUPERUSER -> "bi-shield-exclamation";
            case EXPIRED_PASSWORD, EXPIRING_PASSWORD, NO_PASSWORD_EXPIRY -> "bi-key";
            case EXCESSIVE_PRIVILEGES -> "bi-person-badge";
            case WEAK_AUTH_METHOD, TRUST_AUTHENTICATION, MD5_PASSWORD -> "bi-unlock";
            case PUBLIC_SCHEMA_EXPOSED -> "bi-folder2-open";
            case DANGEROUS_EXTENSION -> "bi-plugin";
            case NO_SSL_CONNECTION -> "bi-shield-x";
            case NO_AUDIT_LOGGING -> "bi-journal-x";
        };
    }

    /**
     * Creates a builder for fluent construction.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for creating SecurityWarning instances.
     */
    public static class Builder {
        private final SecurityWarning warning = new SecurityWarning();

        public Builder type(WarningType type) {
            warning.setType(type);
            return this;
        }

        public Builder severity(Severity severity) {
            warning.setSeverity(severity);
            return this;
        }

        public Builder subject(String subject) {
            warning.setSubject(subject);
            return this;
        }

        public Builder description(String description) {
            warning.setDescription(description);
            return this;
        }

        public Builder recommendation(String recommendation) {
            warning.setRecommendation(recommendation);
            return this;
        }

        public Builder detail(String key, String value) {
            warning.addDetail(key, value);
            return this;
        }

        public SecurityWarning build() {
            return warning;
        }
    }
}
