package com.bovinemagnet.pgconsole.model;

/**
 * Represents a security recommendation generated by the security analysis.
 * <p>
 * Recommendations are categorised by area and prioritised based on
 * the potential security impact.
 *
 * @author Paul Snow
 * @version 0.0.0
 */
public class SecurityRecommendation {

    /**
     * Categories of security recommendations.
     */
    public enum Category {
        ROLES("Roles & Permissions", "bi-people"),
        AUTHENTICATION("Authentication", "bi-key"),
        ENCRYPTION("Encryption", "bi-lock"),
        EXTENSIONS("Extensions", "bi-plug"),
        SCHEMA("Schema", "bi-diagram-3"),
        HBA("Host-Based Auth", "bi-shield-lock"),
        ACCESS_CONTROL("Access Control", "bi-person-lock"),
        LOGGING("Logging & Audit", "bi-journal-text"),
        CONFIGURATION("Configuration", "bi-gear");

        private final String displayName;
        private final String iconClass;

        Category(String displayName, String iconClass) {
            this.displayName = displayName;
            this.iconClass = iconClass;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getIconClass() {
            return iconClass;
        }
    }

    /**
     * Priority levels for recommendations.
     */
    public enum Priority {
        CRITICAL("Critical", "bg-danger", 5),
        HIGH("High", "bg-warning text-dark", 4),
        MEDIUM("Medium", "bg-info", 3),
        LOW("Low", "bg-secondary", 2),
        INFORMATIONAL("Info", "bg-light text-dark", 1);

        private final String displayName;
        private final String cssClass;
        private final int level;

        Priority(String displayName, String cssClass, int level) {
            this.displayName = displayName;
            this.cssClass = cssClass;
            this.level = level;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getCssClass() {
            return cssClass;
        }

        public int getLevel() {
            return level;
        }
    }

    private Category category;
    private Priority priority;
    private String title;
    private String description;
    private String rationale;
    private String suggestedAction;
    private String affectedObject;
    private String currentValue;
    private String recommendedValue;
    private String reference;

    /**
     * Default constructor.
     */
    public SecurityRecommendation() {
    }

    /**
     * Constructs a SecurityRecommendation with the specified attributes.
     *
     * @param category        the recommendation category
     * @param priority        the priority level
     * @param title           short title for the recommendation
     * @param description     detailed description
     * @param suggestedAction what action to take
     */
    public SecurityRecommendation(Category category, Priority priority, String title,
                                   String description, String suggestedAction) {
        this.category = category;
        this.priority = priority;
        this.title = title;
        this.description = description;
        this.suggestedAction = suggestedAction;
    }

    // Getters and Setters

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRationale() {
        return rationale;
    }

    public void setRationale(String rationale) {
        this.rationale = rationale;
    }

    public String getSuggestedAction() {
        return suggestedAction;
    }

    public void setSuggestedAction(String suggestedAction) {
        this.suggestedAction = suggestedAction;
    }

    public String getAffectedObject() {
        return affectedObject;
    }

    public void setAffectedObject(String affectedObject) {
        this.affectedObject = affectedObject;
    }

    public String getCurrentValue() {
        return currentValue;
    }

    public void setCurrentValue(String currentValue) {
        this.currentValue = currentValue;
    }

    public String getRecommendedValue() {
        return recommendedValue;
    }

    public void setRecommendedValue(String recommendedValue) {
        this.recommendedValue = recommendedValue;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    // Helper Methods

    /**
     * Returns the CSS class for the priority badge.
     *
     * @return CSS class name
     */
    public String getPriorityCssClass() {
        return priority != null ? priority.getCssClass() : "bg-secondary";
    }

    /**
     * Returns the display name for the priority.
     *
     * @return priority display name
     */
    public String getPriorityDisplay() {
        return priority != null ? priority.getDisplayName() : "Unknown";
    }

    /**
     * Returns the display name for the category.
     *
     * @return category display name
     */
    public String getCategoryDisplay() {
        return category != null ? category.getDisplayName() : "Unknown";
    }

    /**
     * Returns the icon class for the category.
     *
     * @return Bootstrap icon class
     */
    public String getCategoryIconClass() {
        return category != null ? category.getIconClass() : "bi-question-circle";
    }

    /**
     * Checks if current and recommended values are set.
     *
     * @return true if both values are available
     */
    public boolean hasValueComparison() {
        return currentValue != null && !currentValue.isEmpty() &&
               recommendedValue != null && !recommendedValue.isEmpty();
    }

    /**
     * Creates a builder for fluent construction.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for creating SecurityRecommendation instances.
     */
    public static class Builder {
        private final SecurityRecommendation rec = new SecurityRecommendation();

        public Builder category(Category category) {
            rec.setCategory(category);
            return this;
        }

        public Builder priority(Priority priority) {
            rec.setPriority(priority);
            return this;
        }

        public Builder title(String title) {
            rec.setTitle(title);
            return this;
        }

        public Builder description(String description) {
            rec.setDescription(description);
            return this;
        }

        public Builder rationale(String rationale) {
            rec.setRationale(rationale);
            return this;
        }

        public Builder suggestedAction(String suggestedAction) {
            rec.setSuggestedAction(suggestedAction);
            return this;
        }

        public Builder affectedObject(String affectedObject) {
            rec.setAffectedObject(affectedObject);
            return this;
        }

        public Builder currentValue(String currentValue) {
            rec.setCurrentValue(currentValue);
            return this;
        }

        public Builder recommendedValue(String recommendedValue) {
            rec.setRecommendedValue(recommendedValue);
            return this;
        }

        public Builder reference(String reference) {
            rec.setReference(reference);
            return this;
        }

        public SecurityRecommendation build() {
            return rec;
        }
    }
}
