package com.bovinemagnet.pgconsole.model;

import java.time.Duration;
import java.time.Instant;

/**
 * Represents a stopwatch session for before/after performance comparison.
 * <p>
 * A stopwatch session captures the state of key database metrics at two points in
 * time (start and stop), enabling users to measure the impact of database changes,
 * maintenance operations, or workload shifts. The session records both system-level
 * metrics (connections, cache ratios, transaction rates) and top query snapshots
 * as serialised JSON for detailed before/after comparison.
 * <p>
 * Sessions progress through a simple lifecycle:
 * <ul>
 *   <li><strong>running</strong> - Session is active, capturing the start snapshot</li>
 *   <li><strong>stopped</strong> - Session has been stopped with end snapshot captured</li>
 *   <li><strong>cancelled</strong> - Session was cancelled without capturing end snapshot</li>
 * </ul>
 * <p>
 * Only one session per instance may be in the "running" state at any given time.
 * <p>
 * This class is persisted in the {@code pgconsole.stopwatch_session} table and
 * rendered by the stopwatch dashboard templates.
 *
 * @author Paul Snow
 * @version 0.0.0
 * @see com.bovinemagnet.pgconsole.repository.StopwatchRepository
 * @see com.bovinemagnet.pgconsole.service.StopwatchService
 */
public class StopwatchSession {

    /** Unique identifier for this session, generated by the database. */
    private Long id;

    /** The PostgreSQL instance identifier this session belongs to. */
    private String instanceId;

    /**
     * Current status of the session.
     * Valid values: "running", "stopped", "cancelled".
     */
    private String status;

    /** Timestamp when the session was started. */
    private Instant startedAt;

    /** Timestamp when the session was stopped or cancelled, null if still running. */
    private Instant stoppedAt;

    /** Optional user-provided notes describing the purpose of this session. */
    private String notes;

    /** JSON-serialised metrics snapshot captured at session start. */
    private String startSnapshot;

    /** JSON-serialised metrics snapshot captured at session stop. */
    private String endSnapshot;

    /** JSON-serialised top queries snapshot captured at session start. */
    private String topQueriesStart;

    /** JSON-serialised top queries snapshot captured at session stop. */
    private String topQueriesEnd;

    /** Timestamp when this record was created in the database. */
    private Instant createdAt;

    /**
     * Returns the unique identifier for this session.
     *
     * @return the session id, or null if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for this session.
     *
     * @param id the session id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the PostgreSQL instance identifier this session belongs to.
     *
     * @return the instance identifier (e.g., "default", "production")
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the PostgreSQL instance identifier.
     *
     * @param instanceId the instance identifier
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    /**
     * Returns the current status of the session.
     *
     * @return "running", "stopped", or "cancelled"
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the current status of the session.
     *
     * @param status "running", "stopped", or "cancelled"
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Returns the timestamp when the session was started.
     *
     * @return the start timestamp
     */
    public Instant getStartedAt() {
        return startedAt;
    }

    /**
     * Sets the timestamp when the session was started.
     *
     * @param startedAt the start timestamp
     */
    public void setStartedAt(Instant startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * Returns the timestamp when the session was stopped or cancelled.
     *
     * @return the stop timestamp, or null if still running
     */
    public Instant getStoppedAt() {
        return stoppedAt;
    }

    /**
     * Sets the timestamp when the session was stopped or cancelled.
     *
     * @param stoppedAt the stop timestamp
     */
    public void setStoppedAt(Instant stoppedAt) {
        this.stoppedAt = stoppedAt;
    }

    /**
     * Returns the user-provided notes for this session.
     *
     * @return the notes, or null if none provided
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the user-provided notes for this session.
     *
     * @param notes descriptive notes about the session purpose
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * Returns the JSON-serialised metrics snapshot captured at session start.
     *
     * @return the start snapshot as a JSON string, or null if not captured
     */
    public String getStartSnapshot() {
        return startSnapshot;
    }

    /**
     * Sets the JSON-serialised metrics snapshot captured at session start.
     *
     * @param startSnapshot the start snapshot as a JSON string
     */
    public void setStartSnapshot(String startSnapshot) {
        this.startSnapshot = startSnapshot;
    }

    /**
     * Returns the JSON-serialised metrics snapshot captured at session stop.
     *
     * @return the end snapshot as a JSON string, or null if session is running or cancelled
     */
    public String getEndSnapshot() {
        return endSnapshot;
    }

    /**
     * Sets the JSON-serialised metrics snapshot captured at session stop.
     *
     * @param endSnapshot the end snapshot as a JSON string
     */
    public void setEndSnapshot(String endSnapshot) {
        this.endSnapshot = endSnapshot;
    }

    /**
     * Returns the JSON-serialised top queries snapshot captured at session start.
     *
     * @return the start top queries as a JSON string, or null if not captured
     */
    public String getTopQueriesStart() {
        return topQueriesStart;
    }

    /**
     * Sets the JSON-serialised top queries snapshot captured at session start.
     *
     * @param topQueriesStart the start top queries as a JSON string
     */
    public void setTopQueriesStart(String topQueriesStart) {
        this.topQueriesStart = topQueriesStart;
    }

    /**
     * Returns the JSON-serialised top queries snapshot captured at session stop.
     *
     * @return the end top queries as a JSON string, or null if session is running or cancelled
     */
    public String getTopQueriesEnd() {
        return topQueriesEnd;
    }

    /**
     * Sets the JSON-serialised top queries snapshot captured at session stop.
     *
     * @param topQueriesEnd the end top queries as a JSON string
     */
    public void setTopQueriesEnd(String topQueriesEnd) {
        this.topQueriesEnd = topQueriesEnd;
    }

    /**
     * Returns the timestamp when this record was created in the database.
     *
     * @return the creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the timestamp when this record was created.
     *
     * @param createdAt the creation timestamp
     */
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    // ========================================
    // Helper Methods
    // ========================================

    /**
     * Calculates the elapsed time of this session in seconds.
     * <p>
     * If the session is still running, the elapsed time is calculated from the
     * start time to the current instant. If the session has been stopped or
     * cancelled, the elapsed time is calculated from start to stop.
     *
     * @return the elapsed seconds, or 0 if startedAt is null
     */
    public long getElapsedSeconds() {
        if (startedAt == null) {
            return 0;
        }
        Instant end = (stoppedAt != null) ? stoppedAt : Instant.now();
        return Duration.between(startedAt, end).getSeconds();
    }

    /**
     * Returns the elapsed time formatted as a human-readable string.
     * <p>
     * The format is "Xm Ys" (e.g., "5m 23s" for 5 minutes and 23 seconds).
     * For durations exceeding one hour, the format includes hours (e.g., "1h 5m 23s").
     *
     * @return the formatted elapsed time string
     */
    public String getElapsedDisplay() {
        long totalSeconds = getElapsedSeconds();
        long hours = totalSeconds / 3600;
        long minutes = (totalSeconds % 3600) / 60;
        long seconds = totalSeconds % 60;

        if (hours > 0) {
            return String.format("%dh %dm %ds", hours, minutes, seconds);
        }
        return String.format("%dm %ds", minutes, seconds);
    }

    /**
     * Checks whether this session is currently running.
     *
     * @return true if the session status is "running"
     */
    public boolean isRunning() {
        return "running".equals(status);
    }
}
