pg-console.instances=${PG_CONSOLE_INSTANCES:default,testuni}

## Other databases
#
# Display Name
pg-console.instances.testuni.display-name=Test University
# Connection details
quarkus.datasource.testuni.db-kind=postgresql
quarkus.datasource.testuni.jdbc.url=jdbc:postgresql://localhost:55432/npe_splus
quarkus.datasource.testuni.username=npe_splus
quarkus.datasource.testuni.password=${TESTUNI_PASSWORD:letmein123}

# Re-enable scheduler in dev mode (overrides %dev.quarkus.scheduler.enabled=false)
quarkus.scheduler.enabled=true
