package com.bovinemagnet.pgconsole.service;

import com.bovinemagnet.pgconsole.model.ObjectDifference;
import com.bovinemagnet.pgconsole.model.SchemaComparisonResult;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import jakarta.enterprise.context.ApplicationScoped;
import org.jboss.logging.Logger;

import java.io.ByteArrayOutputStream;

/**
 * Service for generating PDF exports from schema comparison results.
 * <p>
 * Uses OpenHTMLtoPDF to convert HTML to PDF format with proper
 * styling for print output including page breaks, headers, and footers.
 *
 * @author Paul Snow
 * @version 0.0.0
 */
@ApplicationScoped
public class PdfExportService {

    private static final Logger LOG = Logger.getLogger(PdfExportService.class);

    /**
     * Generates a PDF document from a schema comparison result.
     *
     * @param result the schema comparison result to export
     * @return PDF document as byte array
     */
    public byte[] generateSchemaComparisonPdf(SchemaComparisonResult result) {
        LOG.infof("Generating PDF for comparison: %s", result.getDescription());

        String html = generatePrintOptimisedHtml(result);

        try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(html, null);
            builder.toStream(os);
            builder.run();

            LOG.infof("PDF generated successfully, size: %d bytes", os.size());
            return os.toByteArray();
        } catch (Exception e) {
            LOG.errorf(e, "Failed to generate PDF for comparison: %s", result.getDescription());
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    /**
     * Generates print-optimised HTML for PDF conversion.
     *
     * @param result the comparison result
     * @return HTML string optimised for PDF rendering
     */
    private String generatePrintOptimisedHtml(SchemaComparisonResult result) {
        StringBuilder html = new StringBuilder();

        // XML declaration and DOCTYPE for XHTML
        html.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        html.append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" ");
        html.append("\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
        html.append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
        html.append("<head>\n");
        html.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
        html.append("<title>Schema Comparison Report</title>\n");
        html.append("<style type=\"text/css\">\n");
        html.append(getPrintStyles());
        html.append("</style>\n");
        html.append("</head>\n");
        html.append("<body>\n");

        // Header
        html.append("<div class=\"header\">\n");
        html.append("<h1>Schema Comparison Report</h1>\n");
        html.append("<p class=\"subtitle\">Generated by pg-console</p>\n");
        html.append("</div>\n");

        // Metadata
        html.append("<div class=\"metadata\">\n");
        html.append("<table class=\"meta-table\">\n");
        html.append("<tr><td class=\"label\">Source:</td><td>")
                .append(escapeHtml(result.getSourceInstance()))
                .append(".")
                .append(escapeHtml(result.getSourceSchema()))
                .append("</td></tr>\n");
        html.append("<tr><td class=\"label\">Destination:</td><td>")
                .append(escapeHtml(result.getDestinationInstance()))
                .append(".")
                .append(escapeHtml(result.getDestinationSchema()))
                .append("</td></tr>\n");
        html.append("<tr><td class=\"label\">Compared at:</td><td>")
                .append(escapeHtml(result.getComparedAtFormatted()))
                .append("</td></tr>\n");
        html.append("<tr><td class=\"label\">Duration:</td><td>")
                .append(result.getDurationMillis())
                .append(" ms</td></tr>\n");
        html.append("</table>\n");
        html.append("</div>\n");

        // Summary section
        html.append("<div class=\"summary\">\n");
        html.append("<h2>Summary</h2>\n");
        html.append("<div class=\"summary-cards\">\n");
        html.append(createSummaryCard("Missing", result.getSummary().getMissingObjects(), "missing"));
        html.append(createSummaryCard("Extra", result.getSummary().getExtraObjects(), "extra"));
        html.append(createSummaryCard("Modified", result.getSummary().getModifiedObjects(), "modified"));
        html.append(createSummaryCard("Matching", result.getSummary().getMatchingObjects(), "matching"));
        html.append("</div>\n");
        html.append("</div>\n");

        // Differences table
        if (!result.getDifferences().isEmpty()) {
            html.append("<div class=\"differences\">\n");
            html.append("<h2>Differences</h2>\n");
            html.append("<table class=\"diff-table\">\n");
            html.append("<thead>\n");
            html.append("<tr>\n");
            html.append("<th>Type</th>\n");
            html.append("<th>Object Name</th>\n");
            html.append("<th>Status</th>\n");
            html.append("<th>Severity</th>\n");
            html.append("</tr>\n");
            html.append("</thead>\n");
            html.append("<tbody>\n");

            for (ObjectDifference diff : result.getDifferences()) {
                String rowClass = getRowClass(diff.getDifferenceType());
                html.append("<tr class=\"").append(rowClass).append("\">\n");
                html.append("<td>").append(escapeHtml(diff.getObjectType().getDisplayName())).append("</td>\n");
                html.append("<td class=\"object-name\">").append(escapeHtml(diff.getObjectName())).append("</td>\n");
                html.append("<td><span class=\"badge ").append(diff.getDifferenceType().name().toLowerCase())
                        .append("\">").append(escapeHtml(diff.getDifferenceType().getDisplayName()))
                        .append("</span></td>\n");
                html.append("<td><span class=\"badge ").append(diff.getSeverity().name().toLowerCase())
                        .append("\">").append(escapeHtml(diff.getSeverity().getDisplayName()))
                        .append("</span></td>\n");
                html.append("</tr>\n");
            }

            html.append("</tbody>\n");
            html.append("</table>\n");
            html.append("</div>\n");

            // Detailed differences (attribute-level)
            html.append("<div class=\"details\">\n");
            html.append("<h2>Detailed Changes</h2>\n");

            for (ObjectDifference diff : result.getDifferences()) {
                if (!diff.getAttributeDifferences().isEmpty()) {
                    html.append("<div class=\"detail-item\">\n");
                    html.append("<h3>")
                            .append(escapeHtml(diff.getObjectType().getDisplayName()))
                            .append(": ")
                            .append(escapeHtml(diff.getObjectName()))
                            .append("</h3>\n");

                    html.append("<table class=\"attr-table\">\n");
                    html.append("<thead>\n");
                    html.append("<tr><th>Attribute</th><th>Source</th><th>Destination</th></tr>\n");
                    html.append("</thead>\n");
                    html.append("<tbody>\n");

                    for (var attrDiff : diff.getAttributeDifferences()) {
                        html.append("<tr>\n");
                        html.append("<td>").append(escapeHtml(attrDiff.getAttributeName())).append("</td>\n");
                        html.append("<td class=\"source\">")
                                .append(escapeHtml(attrDiff.getSourceValue() != null ? attrDiff.getSourceValue() : "-"))
                                .append("</td>\n");
                        html.append("<td class=\"dest\">")
                                .append(escapeHtml(attrDiff.getDestinationValue() != null ? attrDiff.getDestinationValue() : "-"))
                                .append("</td>\n");
                        html.append("</tr>\n");
                    }

                    html.append("</tbody>\n");
                    html.append("</table>\n");
                    html.append("</div>\n");
                }
            }

            html.append("</div>\n");
        } else {
            html.append("<div class=\"no-differences\">\n");
            html.append("<p>No differences found. The schemas are identical.</p>\n");
            html.append("</div>\n");
        }

        // Footer
        html.append("<div class=\"footer\">\n");
        html.append("<p>Generated by pg-console - PostgreSQL Insight Dashboard</p>\n");
        html.append("</div>\n");

        html.append("</body>\n");
        html.append("</html>");

        return html.toString();
    }

    /**
     * Returns CSS styles optimised for PDF printing.
     */
    private String getPrintStyles() {
        return """
            @page {
                size: A4;
                margin: 2cm;
                @bottom-center {
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 9pt;
                    color: #666;
                }
            }

            body {
                font-family: Helvetica, Arial, sans-serif;
                font-size: 10pt;
                line-height: 1.4;
                color: #333;
                margin: 0;
                padding: 0;
            }

            .header {
                text-align: center;
                margin-bottom: 20pt;
                padding-bottom: 10pt;
                border-bottom: 2pt solid #0d6efd;
            }

            h1 {
                font-size: 18pt;
                color: #0d6efd;
                margin: 0 0 5pt 0;
            }

            .subtitle {
                font-size: 10pt;
                color: #666;
                margin: 0;
            }

            h2 {
                font-size: 14pt;
                color: #333;
                margin: 15pt 0 10pt 0;
                padding-bottom: 5pt;
                border-bottom: 1pt solid #ddd;
            }

            h3 {
                font-size: 11pt;
                color: #555;
                margin: 10pt 0 5pt 0;
            }

            .metadata {
                margin-bottom: 15pt;
            }

            .meta-table {
                width: 100%;
                border-collapse: collapse;
            }

            .meta-table td {
                padding: 3pt 5pt;
                border: none;
            }

            .meta-table .label {
                font-weight: bold;
                width: 100pt;
                color: #555;
            }

            .summary {
                margin-bottom: 20pt;
            }

            .summary-cards {
                display: block;
                width: 100%;
            }

            .summary-card {
                display: inline-block;
                width: 22%;
                margin-right: 2%;
                padding: 10pt;
                text-align: center;
                border-radius: 4pt;
                vertical-align: top;
            }

            .summary-card.missing {
                background-color: #fff3cd;
                border: 1pt solid #ffc107;
            }

            .summary-card.extra {
                background-color: #cfe2ff;
                border: 1pt solid #0d6efd;
            }

            .summary-card.modified {
                background-color: #d1e7dd;
                border: 1pt solid #198754;
            }

            .summary-card.matching {
                background-color: #e2e3e5;
                border: 1pt solid #6c757d;
            }

            .summary-card .count {
                font-size: 18pt;
                font-weight: bold;
                display: block;
            }

            .summary-card .label {
                font-size: 9pt;
                color: #666;
            }

            .diff-table, .attr-table {
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 15pt;
                page-break-inside: auto;
            }

            .diff-table tr, .attr-table tr {
                page-break-inside: avoid;
                page-break-after: auto;
            }

            .diff-table th, .diff-table td,
            .attr-table th, .attr-table td {
                border: 1pt solid #ddd;
                padding: 6pt 8pt;
                text-align: left;
            }

            .diff-table th, .attr-table th {
                background-color: #f8f9fa;
                font-weight: bold;
                color: #333;
            }

            .diff-table tr.row-missing {
                background-color: #fff3cd;
            }

            .diff-table tr.row-extra {
                background-color: #cfe2ff;
            }

            .diff-table tr.row-modified {
                background-color: #d1e7dd;
            }

            .object-name {
                font-family: monospace;
                font-size: 9pt;
            }

            .badge {
                display: inline-block;
                padding: 2pt 6pt;
                border-radius: 3pt;
                font-size: 8pt;
                font-weight: bold;
            }

            .badge.missing {
                background-color: #ffc107;
                color: #000;
            }

            .badge.extra {
                background-color: #0dcaf0;
                color: #000;
            }

            .badge.modified {
                background-color: #0d6efd;
                color: #fff;
            }

            .badge.breaking {
                background-color: #dc3545;
                color: #fff;
            }

            .badge.warning {
                background-color: #ffc107;
                color: #000;
            }

            .badge.info {
                background-color: #0dcaf0;
                color: #000;
            }

            .detail-item {
                page-break-inside: avoid;
                margin-bottom: 15pt;
            }

            .attr-table .source {
                background-color: #f8f8f8;
            }

            .attr-table .dest {
                background-color: #f0f0f0;
            }

            .no-differences {
                padding: 20pt;
                text-align: center;
                background-color: #d1e7dd;
                border-radius: 4pt;
                color: #0a3622;
            }

            .footer {
                margin-top: 20pt;
                padding-top: 10pt;
                border-top: 1pt solid #ddd;
                text-align: center;
                font-size: 9pt;
                color: #666;
            }

            .details {
                page-break-before: auto;
            }
            """;
    }

    /**
     * Creates an HTML summary card.
     */
    private String createSummaryCard(String label, int count, String cssClass) {
        return String.format("""
            <div class="summary-card %s">
                <span class="count">%d</span>
                <span class="label">%s</span>
            </div>
            """, cssClass, count, label);
    }

    /**
     * Gets CSS class for difference row.
     */
    private String getRowClass(ObjectDifference.DifferenceType type) {
        return switch (type) {
            case MISSING -> "row-missing";
            case EXTRA -> "row-extra";
            case MODIFIED -> "row-modified";
        };
    }

    /**
     * Escapes HTML special characters.
     */
    private String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
